(* generated by dune *)

(** @canonical Hardcaml_waveterm_interactive.Draw_notty *)
module Draw_notty = Hardcaml_waveterm_interactive__Draw_notty

(** @canonical Hardcaml_waveterm_interactive.Scroll *)
module Scroll = Hardcaml_waveterm_interactive__Scroll

(** @canonical Hardcaml_waveterm_interactive.Widget *)
module Widget = Hardcaml_waveterm_interactive__Widget

module Hardcaml_waveterm_interactive__ = struct end
[@@deprecated "this module is shadowed"]
