(* generated by dune *)

(** @canonical Hardcaml_waveterm_kernel.Data *)
module Data = Hardcaml_waveterm_kernel__Data

(** @canonical Hardcaml_waveterm_kernel.Data_intf *)
module Data_intf = Hardcaml_waveterm_kernel__Data_intf

(** @canonical Hardcaml_waveterm_kernel.Display_rule *)
module Display_rule = Hardcaml_waveterm_kernel__Display_rule

(** @canonical Hardcaml_waveterm_kernel.Display_rules *)
module Display_rules = Hardcaml_waveterm_kernel__Display_rules

(** @canonical Hardcaml_waveterm_kernel.Draw *)
module Draw = Hardcaml_waveterm_kernel__Draw

(** @canonical Hardcaml_waveterm_kernel.Port *)
module Port = Hardcaml_waveterm_kernel__Port

(** @canonical Hardcaml_waveterm_kernel.Port_name *)
module Port_name = Hardcaml_waveterm_kernel__Port_name

(** @canonical Hardcaml_waveterm_kernel.Render *)
module Render = Hardcaml_waveterm_kernel__Render

(** @canonical Hardcaml_waveterm_kernel.Render_intf *)
module Render_intf = Hardcaml_waveterm_kernel__Render_intf

(** @canonical Hardcaml_waveterm_kernel.Text_alignment *)
module Text_alignment = Hardcaml_waveterm_kernel__Text_alignment

(** @canonical Hardcaml_waveterm_kernel.Wave *)
module Wave = Hardcaml_waveterm_kernel__Wave

(** @canonical Hardcaml_waveterm_kernel.Wave_intf *)
module Wave_intf = Hardcaml_waveterm_kernel__Wave_intf

(** @canonical Hardcaml_waveterm_kernel.Waveform *)
module Waveform = Hardcaml_waveterm_kernel__Waveform

(** @canonical Hardcaml_waveterm_kernel.Waveform_intf *)
module Waveform_intf = Hardcaml_waveterm_kernel__Waveform_intf

(** @canonical Hardcaml_waveterm_kernel.Waves *)
module Waves = Hardcaml_waveterm_kernel__Waves

(** @canonical Hardcaml_waveterm_kernel.Waves_intf *)
module Waves_intf = Hardcaml_waveterm_kernel__Waves_intf

(** @canonical Hardcaml_waveterm_kernel.Write *)
module Write = Hardcaml_waveterm_kernel__Write

module Hardcaml_waveterm_kernel__ = struct end
[@@deprecated "this module is shadowed"]
