(* generated by dune *)

(** @canonical Hardcaml_waveterm.Crypto *)
module Crypto = Hardcaml_waveterm__Crypto

(** @canonical Hardcaml_waveterm.Expect *)
module Expect = Hardcaml_waveterm__Expect

(** @canonical Hardcaml_waveterm.Expect_intf *)
module Expect_intf = Hardcaml_waveterm__Expect_intf

(** @canonical Hardcaml_waveterm.Serialize_waveform *)
module Serialize_waveform = Hardcaml_waveterm__Serialize_waveform

(** @canonical Hardcaml_waveterm.Serialize_waveform_intf *)
module Serialize_waveform_intf = Hardcaml_waveterm__Serialize_waveform_intf

(** @canonical Hardcaml_waveterm.Waveform_digest *)
module Waveform_digest = Hardcaml_waveterm__Waveform_digest

(** @canonical Hardcaml_waveterm.Waveform_digest_intf *)
module Waveform_digest_intf = Hardcaml_waveterm__Waveform_digest_intf

module Hardcaml_waveterm__ = struct end
[@@deprecated "this module is shadowed"]
