(* generated by dune *)

(** @canonical Hardcaml_waveterm_event_store.Bits_store *)
module Bits_store = Hardcaml_waveterm_event_store__Bits_store

(** @canonical Hardcaml_waveterm_event_store.Event_store *)
module Event_store = Hardcaml_waveterm_event_store__Event_store

(** @canonical Hardcaml_waveterm_event_store.Event_store_intf *)
module Event_store_intf = Hardcaml_waveterm_event_store__Event_store_intf
